### ISSUE TITLE
Group Registrations on One Transaction

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#12]
## Issue Overview

For the Black Tie and Boots Importer, we allowed multiple rows to be grouped together on a single transaction. I some customers will want that for this generalized importer too.

In order to support that, there needs to be a way to indicate a group, like a column whose value dictates the group. A "Transaction ID" would be good, but I don't think the source system should need to know about EE transaction IDs.

In Black Tie and Boots, they were grouped by email address. Continuing with that might not be a bad first step.

@joshfeck do you have thoughts on the importance of this feature? (eg should it be in 1.0.0? I suspect it should) Or what would be the best way for a CSV file to indicate multiple rows belong to a single group/transaction?

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

## Expected Behaviour

Some customers may expect there to be a way to group registrations from CSV rows onto shared transactions.

## Current Behaviour

We don't yet import anything; but I suspect without this, each row in the CSV will always be on a new transaction.

## Related Information:

This is different from https://github.com/eventespresso/eea-attendee-importer/issues/11, which was for avoiding duplicate contacts/attendees. This is for sharing transactions across multiple imported registrations.

**Comment by joshfeck** [comment]
One way this could work is have an optional "Group ID" field. If that field is blank then the importer will just import that registration and it will be the only reg. in the transaction. If the Group ID field has a number value that's shared across other registrations in the same import, then only one transaction is created for those registrations.

I don't think this needs to be in v1.

**Comment by mnelson4** [comment]
Kk that sounds like it would work. It would be great if folks gave us a sample CSV needing a feature like this.

**Comment by mnelson4** [comment]
Oh one thing for when we do this: the black-tie-and-boots CSV used the user's email address as the "Group ID". So it's possible more folks will want a mapped column (eg email, or maybe an answer to a custom question) to double as the "Group ID". As I envision Josh's suggestion, that wouldn't be supported because they would need a column dedicated solely to being a group ID- it couldn't also be used for attendee info or a custom question answer.

One way to handle this would be to have a single HTML select input on one of the steps, asking "Which CSV column would you like to use as the Group ID?" Its values would be the CSV columns. 
Eg if they had a csv like this

```
First Name, Last Name, Email Address
Jane, Doe, thedoes@hotmail.com
John, Doe, thedoes@hotmail.com
Steve, Finckle, finckletron@hotmail.com
```

The options for this question would be "First Name", "Last Name", or "Email Address". If they chose "Email Address", then that CSV column can still also be used for the attendee's email address.

Thoughts?

**Comment by joshfeck** [comment]
A column dedicated to a group ID seems simpler to me because it's one less option/decision to make. In other words, if you need to connect registrations into groups, you can add a Group ID field. If you don't, then don't include group ID field. I think it'd be hit or miss for the email address to be used as a group identifier.

**Comment by mnelson4** [comment]
Thanks for the feedback. Yes having a column solely for group identifier may be a simpler UX, and may be sufficient, but in the one use-case I worked on previously they wanted a column to double as group ID and email.
Either way, this isn't part of the MVP. We'll see what users want and do that.
