### ISSUE TITLE
Continue Import

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#25]
## Issue Overview

If someone begins an import and stops partway, it would be great if we could continue it.
By "stops partway", I think that includes both "They got a few steps in, then for some reason closed the window", and "They began the import process, but somehow closed the window".

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by mnelson4** [comment]
@joshfeck would you like this to be part of the MVP?
This may be related to https://github.com/eventespresso/eea-attendee-importer/issues/26, because continuing an import may look very similar to a re-import to some code.

**Comment by joshfeck** [comment]
version 2
