### ISSUE TITLE
Re-importing from the same CSV data should not make duplicate registrations

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#26]
## Issue Overview

While we are currently avoiding creating duplicate attendees when re-importing from the same or similar CSV file, we are not avoiding creating duplicate registrations.

While working on blacktieandboots's importer, they had a CSV that we imported to EE, but they then wanted to update it and re-sync the data (ie, not create duplicates). I think that will be a likely situation going forward, too.

@joshfeck should avoiding duplicate registrations be part of the MVP?

If so, what criteria should be used to identify a duplicate registration? Here's some ideas:

1. We allow a column to be a registration code or something. That could actually go into `REG_code`, and when re-importing, we'd double-check there are no registrations using that code already. If there are, we only update the data instead of adding new data.
2. We treat the attendee ID, and ticket ID- that is, if there is already an attendee registered for that ticket, then it's a duplicate. Except by itself, this doesn't allow an attende to have multiple registations for an event, which is a commonly-sought feature. So this would need some type of tweak to work...
3. We use the CSV file's name and row number as a key- that is, if we import from the same CSV file again, then we assume each row that existed last time we imported is for the same registration. Eg, row 17 was for "Jhon Smith for Ticket 123", and now row is for the same registration data, even though they're name has changed to "John Smith" and the ticket it's now for is 456. This could work, assuming the users ensure to **only add data to the end of the CSV file**. Otherwise, if they replaced row 17 with "Samantha Filbee for Event 789", the code will incorrectly think that's an update to "Jhon Smith for Ticket 123".

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

## Expected Behaviour

When you re-import data from the same source, somehow EE will magically avoid creating duplicate registrations.

## Current Behaviour

Oh we create duplicate registrations like there's no tomorrow.

**Comment by joshfeck** [comment]
version 2
