### ISSUE TITLE
Default option in Ticket Select step is cached from another import

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-importer#39]
## Issue Overview

I have some events and the tickets for each event have different names. So for example Event A has tickets Ticket A and B. Then Event B has Tickets C and D.

I do and import for Event A (and select Ticket A), then after that I try to start an import for Event B. After I select Event B, on step two it shows "Ticket A" as the default choice. Would it be better to not show a default at all in this case? 

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 

Version of this addon:

Version of WordPress:

PHP Version:  

Browser used:

**Comment by sethshoultes** [comment]
I don't think we should show the wrong default ticket, no. I think it would be better to show a default from the tickets assigned to Event B or nothing at all.

**Comment by mnelson4** [comment]
Yeah good catch...

**Comment by joshfeck** [comment]
Fixed in #40
