### ISSUE TITLE
Payment needs to apply to transaction and registration

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-importer#42]
## Issue Overview

In #17 support for importing a payment amount was added. It seems the only item recorded to the db is in the esp_payment columns. The payment amount also needs to be added to the registration (esp_registration_payment) and transaction (esp_transaction.TXN_paid).

Also, if the payment amount is equal to the transaction amount, can we make it so the transaction status and reg status get updated to TCM & RAP, respectively?

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

**Comment by mnelson4** [comment]
Oh nuts, ya I'm reproducing. Thanks for finding this...

**Comment by joshfeck** [comment]
fixed in #43
