### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#44]
## Issue Overview

I'm not too certain who's job it is to get this released on EE.com etc. But I think the first step is assigning someone to take charge of releasing it (optionally, myself). I think you decide who does that right @joshfeck ?

**Comment by garthkoyle** [comment]
@lorenzocaum will be able to help too.

**Comment by garthkoyle** [comment]
@joshfeck what price should we list this at? I know it seems to do a simple thing but: 1) it is valuable if you have to import records, (makes importing possible and saves time/money compared to manual registration) 2) we'll eventually build into it the ability to import events, 3) it may require some support to answer questions and help people with importing.

I'm leaning toward the same price of our other plugins that are kind of like a utility (attendee mover, wait list) for $69.95.

Thoughts?

**Comment by sethshoultes** [comment]
That sounds like a good price.

**Comment by joshfeck** [comment]
The price seems fine to me. I've started a checklist post on P2.

**Comment by mnelson4** [comment]
p2 http://p2.eventespresso.com/2019/06/10/importer-add-on-launch-checklist/

**Comment by lorenzocaum** [comment]
@mnelson4 I'm working on pre-launch tasks for the importer here: https://trello.com/c/sug4l1i0/

I saw a note in Slack eventsmart that you were setting it up with the build machine. Is that the same thing as grunt?

If so, did you already get it set up with the build machine?

**Comment by mnelson4** [comment]
Thanks for checking @lorenzocaum. Yes I set it up with grunt/build machine (grunt is the software our [grunt plugin build machine repository](https://github.com/eventespresso/grunt-wp-plugin-buildmachine) uses). You can tell because there are [commits by EE DevBox Server doing the automatic version bumping.](https://github.com/eventespresso/eea-importer/commit/18f3031a73f12330d75de8380b4681697964d576)

**Comment by lorenzocaum** [comment]
@Pebblo Could you run a release build for the Importer and attach the zip file here?

**Comment by lorenzocaum** [comment]
**Pre-launch notes**

With the Event Espresso Importer add-on, you can import attendees, registrants, and contacts into an upcoming event. Then with the Printable tickets extension, you can optionally email tickets with QR codes so they can be scanned at event check-in with a mobile phone or tablet.

**GitHub slug**: eea-importer

**Recurly plan code**: eea_importer+yearly
**Feature page slug**: eea-importer

**Recurly Event Espresso live:** https://eventespresso.recurly.com/plans/eea_importer+yearly
**Recurly Event Espresso staging:** https://stagingeecom.recurly.com/plans/eea_importer+yearly

**Event Espresso live feature page**: https://docs.google.com/document/d/1K4mUStQfny_IvWSFWwKN1fR2phl60IgJFF1Ncs_wG-0/edit#heading=h.8xzum8msvig1 --> https://eventespresso.com/?post_type=pues2custom_pricing&p=296957&preview=true --> https://eventespresso.com/product/eea-importer/

**Documentation page**: https://docs.google.com/document/d/1iaxw8rX02pmDEGyI2GU7dsADYyRwrDsFrGCE9--F0Xo/edit --> https://eventespresso.com/?post_type=wpwtds_article&p=296963&preview=true --> https://eventespresso.com/wiki/event-espresso-importer-add-on/

**Trello card**: https://trello.com/c/sug4l1i0/
**P2**:

**Comment by lorenzocaum** [comment]
Hey @Pebblo, could you run a release build for the new Importer extension?

**Comment by joshfeck** [comment]
Looks like the grunt build configs were not set up correctly. I'm looking into this now.

**Comment by joshfeck** [comment]
[eea-importer.zip](https://github.com/eventespresso/eea-importer/files/3469008/eea-importer.zip)

**Comment by mnelson4** [comment]
Thanks @joshfeck

**Comment by lorenzocaum** [comment]
Thank you!

**Comment by joshfeck** [comment]
After release:

- [ ] update this topic:
https://eventespresso.com/topic/back-end-bulk-registration/

- [ ] update this trello card:
https://trello.com/c/zvHQNSvF/7-add-on-attendee-import
