### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-importer#46]
## Issue Overview

I am seeing this error when trying to visit the Importer admin page:

`Fatal error: Uncaught UnexpectedValueException: FilesystemIterator::__construct(/home2/web801/public_html/ee4-testing/wp-content/plugins/eea-importer-master/src/domain/services/import/csv/attendees/forms/form_handlers/UploadCsv/): failed to open dir: No such file or directory in /home2/web801/public_html/ee4-testing/wp-content/plugins/event-espresso-core-reg/core/services/locators/FqcnLocator.php:107 Stack trace: #0 /home2/web801/public_html/ee4-testing/wp-content/plugins/event-espresso-core-reg/core/services/locators/FqcnLocator.php(107): FilesystemIterator->__construct('/home2/web801/p...') #1 /home2/web801/public_html/ee4-testing/wp-content/plugins/event-espresso-core-reg/core/services/locators/FqcnLocator.php(85): EventEspresso\core\services\locators\FqcnLocator->findFQCNsByNamespace('EventEspresso\\A...') #2 /home2/web801/public_html/ee4-testing/wp-content/plugins/event-espresso-core-reg/core/services/collections/CollectionDetails.php(362): EventEspresso\core\services\locators\FqcnLocator->locate('EventEspresso\\A... in /home2/web801/public_html/ee4-testing/wp-content/plugins/event-espresso-core-reg/core/services/collections/CollectionDetails.php on line 174`

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.81.p

Version of this addon: 1.0.0.dev.000

Version of WordPress: 5.2.1

Browser used:  Chrome

## Steps to Reproduce (for bugs)
Install plugin, visit Import admin page.

**Comment by sethshoultes** [comment]
@mnelson4 I created an account for you on my testing site. You should have received an email about it. Here's the admin page where the error appears: http://801website.com/ee4-testing/wp-admin/admin.php?page=espresso_importer

**Comment by mnelson4** [comment]
Thanks huh ya I'm not reproducing that locally, I'm debugging this now...

**Comment by mnelson4** [comment]
FYI I uploaded a fixed branch of the importer add-on onto your site @sethshoultes, so you should be able to continue trying it out.

**Comment by sethshoultes** [comment]
Thanks! That fixed it. However, I found a different issue here:
https://github.com/eventespresso/eea-importer/issues/49

**Comment by mnelson4** [comment]
Pr resolved this isssue. Onto the next!
