### ISSUE TITLE
Doesn't import multi-valued answers

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-importer#49]
## Issue Overview
While testing on this site, I noticed that the import process can import single value answers but it doesn't seem to be importing the multi-valued answers for checkbox and multi-select questions. 

I'm using the example csv (simple-with-custom-questions.csv) while testing:
![simple-with-custom-questions 2019-06-10 16-38-31](https://user-images.githubusercontent.com/235315/59231566-5fcee900-8b9e-11e9-9217-b6052fe0fa1f.jpg)

Importing those records doesn't seem to capture the multivalue answers:
![‹ EE4 Testing — WordPress 2019-06-10 16-38-16](https://user-images.githubusercontent.com/235315/59231589-79703080-8b9e-11e9-9901-d9ade3e9d55c.jpg)

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.81.p

Version of this addon: 1.0.0.dev.000

Version of WordPress: 5.2.1

Browser used: Firefox

## Steps to Reproduce (for bugs)

Upload the example csv into event a: 
http://801website.com/ee4-testing/wp-admin/admin.php?page=espresso_importer&action=import&type=csv-attendee&import_nonce=6fd2174a08

**Comment by mnelson4** [comment]
dang, I could have sworn that was working at one point (which is why it's in the sample CSV). But thanks for catching that... lemme see...

**Comment by joshfeck** [comment]
Linking this PR: #54

**Comment by joshfeck** [comment]
fixed in #54
