### ISSUE TITLE
Link for sample CSV file is broken

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-importer#51]
**Summary**
I've started testing out the Attendee Importer on Make Events Not War staging. I was looking for an example CSV file and the link to one is broken:

![Image 2019-06-13 at 9 41 44 AM](https://user-images.githubusercontent.com/1079138/59437443-9cc5f600-8dbf-11e9-9697-3fb9dd27e852.png)

It points here: https://lorenzo1072.makeeventsnotwar.com/wp-content/plugins/eea-importer/samples/simple-with-custom-questions.csv

**Comment by lorenzocaum** [comment]
https://github.com/eventespresso/eea-importer/blob/master/samples/attendee-with-custom-questions.csv

**Comment by mnelson4** [comment]
thanks @lorenzocaum  and @joshfeck ! 👍
