### ISSUE TITLE
Getting stuck on step 4: Map CSV columns

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-importer#52]
**Summary**
I'm exploring how the importer works here with my staff account:

https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer

I got a copy of the sample file and then populated it so it has the same system questions as Event Espresso. For example, I added a Last Name column, renamed Street Address to Address and so forth.

Here is the file: https://cl.ly/52164b5ded8c/download/test-info-with-address-questions.csv

On step 4 it looks incomplete like this:

![Image 2019-06-13 at 1 35 36 PM](https://user-images.githubusercontent.com/1079138/59454468-27b6e880-8de0-11e9-9a5e-a277634a8757.png)

I then tried another CSV where it is just the First Name, Last Name, Email Address, and Payment Amount but that didn't work either. Here is that other CSV file: https://cl.ly/fbfa50b2d685/download/test-info-personal-questions-only.csv

I also tried other events but they all look similar to the screenshot above. If I select something and try to move forward, then the page refreshes.

**Steps to reproduce**
Same as above

**Reported or seen on**
https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer

**Other notes**

Nothing in Rapid 7 logs:

https://eu.ops.insight.rapid7.com/op/3C2621E689F216EF69EE#/search?logs=%5B%2227231556-ebec-48d8-b8ef-d51bf31a7761%22%2C%2231596140-8113-4bbd-be59-b0aee1fc821f%22%5D&query=where(NOT%20Hook%3A)&range=Last%201%20Hour

**Comment by lorenzocaum** [comment]
I did some more digging and I think this is related to how Apple Numbers handles exporting of CSV files.

I copied the same information into Google sheets and then exported to a CSV and now it looks like it will work:

![Image 2019-06-13 at 1 45 56 PM](https://user-images.githubusercontent.com/1079138/59455146-947eb280-8de1-11e9-876b-319b1c499dae.png)

![Image 2019-06-13 at 1 47 09 PM](https://user-images.githubusercontent.com/1079138/59455232-c09a3380-8de1-11e9-9802-bc97a0ab9c85.png)

**Comment by mnelson4** [comment]
hmmm I bet a good number of our users may encounter that same issue with Apple numbers. Should we document this issue? Alternatively we could handle the issue fairly easily: I see the CSV you produced contained a line of blank cells (ie it was literally `,,,,,,,,,,`). We could check for that when trying to read for column headers. Or if you really think it's a non-issue, we can leave as-is.

**Comment by joshfeck** [comment]
I didn't have any issues exporting CSV's from Apple Numbers earlier when testing this.

**Comment by mnelson4** [comment]
Oh weird. So maybe it was an isolated issue? I'm ok with closing too

**Comment by mnelson4** [comment]
ok ok, so let's just reopen this if anyone else ever experiences it
