### ISSUE TITLE
Importing same line twice?

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#53]
## Issue Overview

I'm seeing that we're somehow importing the same line twice now? I'm seeing nothing but Sally Andersons after an import. 

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

Run the importer on the sample CSV. 

## Expected Behaviour

One should be for the 2nd row, Stu.

## Current Behaviour

Somehow I'm seeing two new registrations for Sally Anderson.

**Comment by mnelson4** [comment]
Aha, I see what's going on: WP user integration add-on isn't playing nicely.
When importing the attendee, we first check for duplicates, and eventually call `\EventEspresso\core\services\commands\attendee\CreateAttendeeCommandHandler::findExistingAttendee()`, which applies the filter `FHEE_EventEspresso_core_services_commands_attendee_CreateAttendeeCommandHandler__findExistingAttendee__existing_attendee`, which gets filtered in `EE_Deprecated` and in turn applies the filters of `FHEE_EE_Single_Page_Checkout__save_registration_items__find_existing_attendee`, which `EED_WP_Users_SPCO::maybe_sync_existing_attendee()` filters, and replaces the found user with the user attached to the logged-in user.
I think basically we didn't expect anyone to be using `CreateAttendeeCommand` unless they were in SPCO. 
The quickfix would be for the importer add-on to just unhook the WP users filter callback, but that feels a little hacky. Alterniatvely, maybe SPCO or WP Users add-on should check if this is an attendee being created via SPCO, and if not, don't execute its attendee-info-syncing logic. @tn3rb do you have any wise ideas from the SPCO perspective? If not, maybe I'll ask Darren if he has anything from the WP Users add-on perspective.

**Comment by mnelson4** [comment]
Thinking some more: I think I should just have a quickfix that unhooks the WP user integration add-ons filters when importing; and we can thereafter explore any more proper solutions. Thoughts @tn3rb ?

**Comment by tn3rb** [comment]
not only is unhooking the WP_User addons filters a quickfix, imho it is the absolute best fix since there is no way that the correct user is going to be logged in when doing the import.

**Comment by joshfeck** [comment]
Fixed in #59
