### ISSUE TITLE
404 on /eea-importer-master/src/admin/importer/assets/espresso_importer_admin.js?ver=1.0.0.dev.000

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-importer#56]
**Summary**
In #55, I was trying to figure out why the Attendee Importer isn't working on Make Events Not War staging but is working on my other website.

I inspected the page on my local site and saw a 404 on this file:

`/eea-importer-master/src/admin/importer/assets/espresso_importer_admin.js?ver=1.0.0.dev.000`

**Steps to reproduce**
Add a copy of the importer add-on to your site. Then go to the Importer page and inspect it with dev tools.

**Reported or seen on**
You can reproduce this on multiple sites.

**Comment by mnelson4** [comment]
Hmmm I'm not reproducing that issue locally. That issue may have just been fixed recently in master. Let's check again next time it gets updated on MENW?

**Comment by lorenzocaum** [comment]
Hi Mike, I got an updated copy of the Importer and added to my testing site. I see the same thing with the 404 while viewing the importer page.

You can see it on the playground site too. I added a copy of core master and the attendee importer master:

https://playground.eventespresso.com/wp-admin/admin.php?page=espresso_importer

**Comment by joshfeck** [comment]
Fixed in #62
