### ISSUE TITLE
Registrations have status pending payment even though paid

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-importer#66]
## Issue Overview

When I import a registration with a payment, even if the registration is paid in full, it still shows 'pending payment' for the registration (but the transaction is complete)

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.83.rc.012

Version of this addon:1.0.0

Version of WordPress:5.2

PHP Version:  7.1

Browser used:  Firefox

## Steps to Reproduce (for bugs)

Import registrations from the sample CSV to a paid event costing $10. Map the payment column so they get a payment. 

## Expected Behaviour

The row with a $5 payment should be pending payment, but the row with a $10 should be approved.

## Current Behaviour

Even though the row with a $10 payment is paid, its status will be "pending payment."

**Comment by joshfeck** [comment]
fixed in #67
